### ISSUE TITLE
您好，报一个错误AttributeError: module 'ruamel.yaml' has no attribute 'round_trip_load'没解决掉

### ISSUE THREAD

**Issue by LXX230** [DL-Practise/YoloAll#7]
![图片](https://user-images.githubusercontent.com/74136966/144377975-5c05440b-e4fa-4a7b-b1ba-413824a1fb5c.png)

**Comment by DL-Practise** [comment]
我这边没有复现这个问题呢。能否提供一下ruamel的版本信息，以及你运行的操作系统，python版本等信息

**Comment by LXX230** [comment]
已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DL-Practise/YoloAll"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DL-Practise/YoloAll] 您好，报一个错误AttributeError: module 'ruamel.yaml' has no attribute 'round_trip_load'没解决掉 (Issue #7)





 
我这边没有复现这个问题呢。能否提供一下ruamel的版本信息，以及你运行的操作系统，python版本等信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Epiphany7725** [comment]
你好，请问您是如何解决的
